@startuml

entity "User" as User {
    +id: UUID
    +name: String
    +role: String
    +status: String
}

entity "Ride" as Ride {
    +id: UUID
    +fare_id: UUID
    +user_id: UUID
    +driver_id: UUID
    +source: GeoLocation
    +destination: GeoLocation
    +status: String
}

entity "Fare" as Fare {
    +id: UUID
    +ride_id: UUID
    +fare_estimation: Float
}

entity "Location" as Location {
    +user_id: UUID
    +latitude: Float
    +longitude: Float
}

User "1" -- "N" Ride 
User "1" -- "N" Location 
Ride "1" -- "1" Fare 

@enduml